name: Main

on:
  push:
    branches:
      - Develop  # Change this to your default branch
  pull_request:
      branches:
      - Develop  # Change this to your default branch

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GitLeaks
      run: |
        wget -O gitleaks https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
        tar -xvzf gitleaks.tar.gz
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/

    - name: Run GitLeaks Secret Scan
      run: |
        gitleaks detect --redact
      env:
        GL_CONFIG: .gitleaks.toml  # Optional: Use a GitLeaks configuration file

    # Add additional steps here if needed, such as sending notifications or taking actions based on the scan results.
